version: "3"

services:
    db:
        image: postgres:latest
        container_name: fonote-postgres
        environment:
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        restart: always

    web:
        hostname: web
        build:
            context: .
            dockerfile: ./Dockerfile
        container_name: fonote-django
        command: >
            bash -c "
                python manage.py collectstatic --no-input &&
                python manage.py migrate --no-input &&
                gunicorn core.wsgi:application -w 4 -b 0.0.0.0:8000"
        volumes:
          - ./backend:/app
        ports:
            - "8000:8000"
        depends_on:
            - redis
            - celery
        env_file:
            - .env
        restart: always

    redis:
        image: redis:latest
        container_name: fonote-redis
        ports:
            - "6379:6379"
        restart: always

    celery:
        build:
            context: .
            dockerfile: ./Dockerfile
        container_name: fonote-celery
        command: celery -A core.celery worker -l info
        volumes:
            - ./backend:/app/
        depends_on:
            - redis
        restart: always

    celery-beat:
        build:
            context: .
            dockerfile: ./Dockerfile
        container_name: fonote-celery-beat
        command: celery -A core.celery beat -l info
        volumes:
            - ./backend:/app/
        depends_on:
            - redis