# Generated by Django 5.0.4 on 2024-04-18 16:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_plan_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
