# Generated by Django 5.0.4 on 2024-04-18 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0006_alter_price_prev_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='prev_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
