# Generated by Django 5.0.4 on 2024-04-18 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0007_alter_price_prev_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='session_id',
            field=models.CharField(default='a', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('ACTIVE', 'ACTIVE'), ('CANCELED', 'CANCELED'), ('EXPIRED', 'EXPIRED')], default='PENDING', max_length=25),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
