# Generated by Django 5.0.4 on 2024-04-18 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0010_alter_usersubscription_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
