# Generated by Django 5.0.4 on 2024-04-19 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0013_order_invoice_id_alter_order_currency_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='plan',
            options={'verbose_name': 'Plan', 'verbose_name_plural': 'Plans'},
        ),
        migrations.AlterModelOptions(
            name='price',
            options={'verbose_name': 'Price', 'verbose_name_plural': 'Prices'},
        ),
        migrations.AlterModelOptions(
            name='usersubscription',
            options={'ordering': ['-created_at'], 'verbose_name': 'UserSubscription', 'verbose_name_plural': 'UserSubscriptions'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='invoice_url',
        ),
        migrations.RemoveField(
            model_name='order',
            name='stripe_id',
        ),
    ]
