# Generated by Django 5.0.4 on 2024-04-21 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0014_alter_order_options_alter_plan_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='ai_transcription',
        ),
    ]
