# Generated by Django 5.0.4 on 2024-04-25 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0018_plan_change_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='ai_transcription',
            field=models.BooleanField(default=False),
        ),
    ]
