# Generated by Django 5.0.4 on 2024-05-05 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0020_plan_max_input_alter_plan_max_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='max_length',
        ),
    ]
