# Generated by Django 5.0.4 on 2024-05-05 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0021_remove_plan_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='web',
            field=models.BooleanField(default=False),
        ),
    ]
