# Generated by Django 5.0.4 on 2024-04-17 23:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InputData',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('YOUTUBE', 'YOUTUBE'), ('SPOTIFY', 'SPOTIFY')], max_length=25)),
                ('transcription_type', models.CharField(choices=[('GENERATED', 'GENERATED'), ('MANUAL', 'MANUAL'), ('LLM', 'LLM')], max_length=25)),
                ('audio_length', models.IntegerField(blank=True, null=True)),
                ('source_title', models.CharField(blank=True, max_length=255, null=True)),
                ('source_url', models.URLField()),
                ('status', models.CharField(choices=[('NEW', 'NEW'), ('PROCESSING', 'PROCESSING'), ('DONE', 'DONE'), ('ERROR', 'ERROR')], default='NEW', max_length=25)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
    ]
