# Generated by Django 5.0.4 on 2024-04-20 00:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_alter_inputdata_options_alter_result_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inputdata',
            name='language',
            field=models.CharField(choices=[('Danish', 'Danish'), ('Czech', 'Czech'), ('Dutch', 'Dutch'), ('English', 'English'), ('German', 'German'), ('Italian', 'Italian'), ('Japanese', 'Japanese'), ('Korean', 'Korean'), ('Polish', 'Polish'), ('Spanish', 'Spanish')], default='Polish', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inputdata',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
