# Generated by Django 5.0.4 on 2024-04-20 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0005_fragment_alter_inputdata_language_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inputdata',
            name='youtube_fragments',
        ),
        migrations.AddField(
            model_name='fragment',
            name='input_data',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fragments', to='ai.inputdata'),
            preserve_default=False,
        ),
    ]
