# Generated by Django 5.0.4 on 2024-04-26 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0010_alter_result_result_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fragment',
            name='end_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fragment',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fragment',
            name='start_time',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
